### ISSUE TITLE
装了插件，但是文件名不识别

### ISSUE THREAD

**Issue by huangge1199** [berserk-112/nowcoder-editor#2]
![image](https://user-images.githubusercontent.com/9335756/218626706-58742af7-a003-4026-afa1-46f19144e1f1.png)

idea版本：2022.3.2
Code FileName：$!velocityTool.camelCaseName(${question.titleSlug})
Code Template
${question.content}
package nowcoder.editor.cn;

// $!{question.frontendQuestionId}:${question.title}
public class $!velocityTool.camelCaseName(${question.titleSlug}){
    public static void main(String[] args) {
        Solution solution = new $!velocityTool.camelCaseName(${question.titleSlug})().new Solution();
        // TO TEST
    }
    ${question.code}
}

**Comment by berserk-112** [comment]
牛客网修改了题目的api,花了点时间做了替换；
另外牛客网中的题目是没有英文标题的，我使用题目模板代码中的方法名作为question.titleSlug，但是这会造成部分方法名相同的题目无法打开，临时的解决方法是修改项目中重名的代码文件。

已经提交了update,等审核通过，更新插件即可解决当前问题。
