### ISSUE TITLE
获取题目为空，请尝试重新从面板打开题目

### ISSUE THREAD

**Issue by yingxiangyu** [berserk-112/nowcoder-editor#3]
选择公司题库，打开后无法提交测试

**Comment by berserk-112** [comment]
看了下，牛客网获取公司题库的api和普通题目的api不一样，过段时间我会更新的。
另外使用custom template功能的话，由于公司题库中题目的方法名都是main这会有点问题。

**Comment by berserk-112** [comment]
hi，很抱歉拖了这么久。插件已经更新了，有些公司题库中的题目是没有核心代码模板的。目前解决方法是对于这些题目，将统一使用预设的acm模板。欢迎更新插件并使用。
