### ISSUE TITLE
请问怎么选择ACM模式

### ISSUE THREAD

**Issue by Yuminis98** [berserk-112/nowcoder-editor#4]
现在好像是关键代码模式，请问怎么切换成ACM模式？

**Comment by berserk-112** [comment]
目前是无法切换的，可以考虑勾选设置中的custom template 功能。

**Comment by berserk-112** [comment]
今天又仔细看了下，牛客网的acm模式模板应该是固定的，当题目中没有核心代码模板时会使用固定的acm模板，例如[这题](https://www.nowcoder.com/practice/afe812c80ad946f4b292a26dd13ba549)。顺利的话，我这周会更新下插件，实现自动填充acm模板功能（或许可以在设置里增加个acm模板选项，这样打开每个题目模板都会是一样的）。

**Comment by berserk-112** [comment]
hi, 插件已经更新。没有默认核心代码模板的题目，会加载默认的acm模板，不允许手动替换模式。欢迎使用。
