### ISSUE TITLE
不能和leetcode的插件共存吗

### ISSUE THREAD

**Issue by OTraveler** [berserk-112/nowcoder-editor#5]
idea版本是2022.2，重启后提示两个插件不能同时运行.
the plugins below cannot function at the same time.

**Comment by berserk-112** [comment]
是的，目前不能和leetcode的插件同时进行。之后有空的话我再看看能否做的并存，感谢使用！

**Comment by berserk-112** [comment]
是的，目前不能和leetcode的插件同时进行。之后有空的话我再看看能否做的并存，感谢使用！

**Comment by berserk-112** [comment]
已经更新了插件，待审核通过后即可安装更新即可解决不能和leetcode插件共存问题。
